/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as IndexRouteImport } from './routes/index'

const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/drinks': typeof DrinksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/drinks': typeof DrinksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/drinks': typeof DrinksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adventure' | '/drinks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adventure' | '/drinks'
  id: '__root__' | '/' | '/adventure' | '/drinks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventureRoute: typeof AdventureRoute
  DrinksRoute: typeof DrinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventureRoute: AdventureRoute,
  DrinksRoute: DrinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
